# Generated by Django 3.1.7 on 2021-03-31 01:54

from django.db import migrations, models
import django.db.models.deletion
import question.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_number', models.IntegerField(default=1, verbose_name='実験番号')),
                ('user', models.CharField(default='none', max_length=50, verbose_name='ユーザー名')),
                ('judge', models.CharField(default='none', max_length=20, verbose_name='正誤')),
                ('time', models.IntegerField(default=0, verbose_name='回答時間')),
                ('question_number', models.IntegerField(default=0, verbose_name='問題番号')),
                ('correct', models.CharField(default='none', max_length=100, verbose_name='正解')),
                ('answer', models.CharField(blank=True, max_length=100, verbose_name='回答')),
            ],
            options={
                'verbose_name': '回答データ',
                'verbose_name_plural': '回答データ',
            },
        ),
        migrations.CreateModel(
            name='QuestionTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='問題タイトル')),
                ('about', models.TextField(blank=True, verbose_name='問題概要')),
                ('image', models.ImageField(blank=True, default='images/question.png', upload_to='images/', verbose_name='問題画像')),
            ],
            options={
                'verbose_name': '問題タイトル',
                'verbose_name_plural': '問題タイトル',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_number', models.IntegerField(default=1, verbose_name='実験番号')),
                ('number', models.IntegerField(default=0, verbose_name='問題番号')),
                ('question', models.CharField(max_length=200, verbose_name='問題')),
                ('correct', models.CharField(max_length=200, verbose_name='正解')),
                ('title', models.ForeignKey(default=question.models.QuestionTitle, on_delete=django.db.models.deletion.CASCADE, related_name='title_question', to='question.questiontitle', verbose_name='タイトル')),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題',
            },
        ),
    ]
